
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import '@radix-ui/themes/styles.css';
import { NextAuthProvider } from './provider'
import Image from 'next/image'
import {  List, MagnifyingGlass, MapPin, ShoppingBag } from '@phosphor-icons/react/dist/ssr/index'
import Navbar from './components/layout/navbar'
import Head from 'next/head'

const yekan = localFont({
  src: [
    {
      path: './public/font/YEKAN-PLUS.ttf',
      weight: '400'
    },
  ],
  variable: '--font-yekan'
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa"  >
      
      <body className={yekan.variable}>
        
      <NextAuthProvider>
        <div className='min-h-[100vh] w-full font-yekan ' >
        <Navbar/>
        {children}
        </div>
      </NextAuthProvider>
        </body>
    </html>
  )
}
