import "./globals.css";
import "@radix-ui/themes/styles.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";

import Provider from "./lib/query/provider";
import { NextAuthProvider } from "./provider";

const yekan = localFont({
  src: [
    {
      path: "./public/font/YEKAN-PLUS.ttf",
      weight: "400"
    },
  ],
  variable: "--font-yekan"
});
export const metadata: Metadata = {
  title: "فروشگاه اینترنتی NextShop",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">

      <body className={yekan.variable}>
        <NextAuthProvider>
          <Provider>
            <div className="min-h-[100vh] bg-white w-full font-yekan ">
              {children}
              <Toaster />
            </div>
          </Provider>
        </NextAuthProvider>

      </body>
    </html>
  );
}
